/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import net.buj.surreal.Driver;
import net.buj.surreal.EventCallback;
import net.buj.surreal.Query;
import net.buj.surreal.Response;
import net.buj.surreal.SurrealURL;

import static org.junit.Assert.*;

import java.util.Objects;
import java.util.Random;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class LibraryTest {
    public static class SurrealUrlNotSpecifiedException extends RuntimeException {
        public SurrealUrlNotSpecifiedException(String message) {
            super(message);
        }

        public static String getSurrealUrl() {
            String env = System.getenv("SURREAL_URL");
            if (env == null)
                throw new SurrealUrlNotSpecifiedException("SURREAL_URL must be set for tests to work");
            return env;
        }
    }

    public static String connectionUrl = SurrealUrlNotSpecifiedException.getSurrealUrl();

    @Test
    public void urlParseTest() throws Exception {
        Driver driver = new Driver(connectionUrl);
        CountDownLatch wait = new CountDownLatch(1);
        Exception[] error = new Exception[1];
        boolean[] complete = new boolean[] { false };

        driver.onConnect(new EventCallback<Object>() {
            @Override
            public void run(Object value) {
            }

            @Override
            public void fail(Exception why) {
                synchronized (error) {
                    error[0] = why;
                }
                wait.countDown();
            }
        });

        int nonce = new Random().nextInt();

        driver.query(new Query(
                "define table __surrealrpctest;" + "create __surrealrpctest content { nonce: $nonce };")
                .x("nonce", nonce),
                new EventCallback<Response[]>() {
                    @Override
                    public void run(Response[] value) {
                        try {
                            for (Response r : value)
                                r.ok();
                        } catch (Exception e) {
                            throw new RuntimeException(e);
                        }

                        driver.query(
                                new Query("select value nonce from __surrealrpctest; remove table __surrealrpctest;"),
                                new EventCallback<Response[]>() {
                                    @Override
                                    public void run(Response[] value) {
                                        try {
                                            for (Response r : value)
                                                r.ok();
                                        } catch (Exception e) {
                                            throw new RuntimeException(e);
                                        }

                                        if (value[0].result.asJsonList().get(0).asInteger() == nonce)
                                            synchronized (complete) {
                                                complete[0] = true;
                                            }
                                        else
                                            error[0] = new Exception("Invalid nonce");

                                        wait.countDown();
                                    }

                                    @Override
                                    public void fail(Exception why) {
                                        synchronized (error) {
                                            error[0] = why;
                                        }
                                        wait.countDown();
                                    }
                                });
                    }

                    @Override
                    public void fail(Exception why) {
                        synchronized (error) {
                            error[0] = why;
                        }
                        wait.countDown();
                    }
                });

        wait.await(5, TimeUnit.SECONDS);
        driver.close();

        synchronized (error) {
            if (error[0] != null)
                throw error[0];
        }
        synchronized (complete) {
            if (complete[0] == false)
                throw new Exception("Took too long to complete");
        }
    }
}
